version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1

on:
  pull_request:
    types: [closed]
    
jobs:
  create-flask-ec2:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:          
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          aws-region: AWS_REGION_NAME
      - run: >-
          aws ec2 run-instances --image-id ami-0557a15b87f6559cf --count 1 --instance-type t2.micro --security-group-ids sg-0d137402e346309e6 --user-data file://configs/user_data.sh
workflows:
  aws-cli:
    jobs:
      - create-flask-ec2